### ISSUE TITLE
Allow upper and lower label at the same time

### ISSUE THREAD

**Issue by louy2** [mredaelli/circuitikz#14]
Or please instruct on how to label the name and the value of an element at the same time.

**Comment by mredaelli** [comment]
Give a name to the component, and then place a new node relative to that:
```
(0,0) to[R=R, name=res] (2,0)
(res.south) node[below] {E}
```

**Comment by louy2** [comment]
Thanks! Will this hack go into the package in some way?

**Comment by mredaelli** [comment]
What do you mean? You can already use it. It's not a hack, just standard
TikZ syntax.

Maybe I should check if the option "name" is documented, though... I think
it is.

**Comment by louy2** [comment]
I mean something like `(0,0) to[R, l^=up, l_=down] (2,0)`.

**Comment by louy2** [comment]
Btw, `R=R` is not documented. What does it do?

**Comment by mredaelli** [comment]
Sure it is: page 24 here: http://texdoc.net/texmf-dist/doc/latex/circuitikz/circuitikzmanual.pdf

Which is why I'm dubious to add support for both labels, as it won't be clear which one would override the R= label

**Comment by louy2** [comment]
Oh, only searched for `R=R`. "Didn't see that coming. " -- Quote Hawkeye. So the first argument serves both as a type indicator and a value label.

It's a strange choice for me. Now label `R, l=` is only a replacement of `R=`? They seem to never appear together.

The main problem when I use circuitikz is often I can't both label and present value, which is common in the undergraduate course I am taking. For sources because `v` and `i` are used, I can work around this with `l`, but I can't do so with resistors. There seems no such distinction between variable name label and value label in the documentation, seeing that `V, v=` substitutes `V=` and `I, i=` substitutes `I=`. Maybe use `R, r=` to substitute `R=` and free up both labels?

**Comment by mredaelli** [comment]
The general assumption is that the syntax simplifies the most common pattern, and as far as I'm concerned the most useful label for a voltage source is the voltage, for a current source the current, and for a resistor the resistance.
`R, r=` couldn't free up both labels, because one is used by `r=` itself.

I personally hate overloaded symbols, such as having a label both above and below a resistor (seems to be working with PSpice, yuch), and rarely if ever feel the need to put both name and value.
When that happens, I just write `to[R=$R_1{=}\SI{1}{\ohm}$]`.

**Comment by louy2** [comment]
Thank you for the explanation.
