### ISSUE TITLE
add ability to use inversion bubbles on selected inputs of logic gates

### ISSUE THREAD

**Issue by jason-s** [mredaelli/circuitikz#15]
Buffers and AND/OR/XOR gates should be able to use inversion bubbles on the inputs.

http://tex.stackexchange.com/questions/97644/circuitikz-inverter-bubble

**Comment by mredaelli** [comment]
Gates in CircuiTikz are decisively inferior to those in the official TikZ library, mostly because there you have support for an arbitrary number of inputs -- which would be difficult to implement here, I'm afraid.

So, if you already switched to plain TikZ, I won't even try :) Otherwise, if there's actually people wanting me to, I might start with a large-scale overhauling of all the gates code -- but that's gonna take some time :P

**Comment by jason-sachs** [comment]
ok, if you like the tikz gates better (I didn't realize it had any!) I agree it makes no sense to add this in circuitikz... maybe you could give an example of using the tikz gates with inversion bubbles?

**Comment by mredaelli** [comment]
Here you can find an example:
http://www.texample.net/tikz/examples/logic-circuits-library/

**Comment by jason-s** [comment]
good god, those OR-gates look ugly. But they'll do. thanks!
